[package]
name = "detecta-fraude"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"

[lib]
name = "detecta_fraude"
path = "src/lib.rs"

[[bin]]
name = "fraud-api"
path = "src/bin/fraud-api.rs"

[[bin]]
name = "index-builder"
path = "src/bin/index-builder.rs"

[dependencies]
libc = "0.2"
memmap2 = "0.9"

[build-dependencies]

[target.'cfg(target_os = "linux")'.dependencies]

[features]
default = []
builder = ["dep:flate2", "dep:serde_json"]
knn_stats = []

[dependencies.flate2]
version = "1"
optional = true

[dependencies.serde_json]
version = "1"
optional = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug = false

[profile.release.package."*"]
opt-level = 3
